version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: taskmanager_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskmanager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskmanager_network

  backend:
    build: ./backend
    container_name: taskmanager_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/taskmanager?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production_1234567890
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - taskmanager_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: taskmanager_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - taskmanager_network

volumes:
  mongodb_data:

networks:
  taskmanager_network:
    driver: bridge
