version: '3.8'

networks:
  taskmanager-network:
    driver: bridge

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://prisma:1234@cluster0.flmxcne.mongodb.net/taskmanager
      - JWT_SECRET=Oxfordfreepass4$
      - JWT_EXPIRES_IN=7d
      - EMAIL_PROVIDER=gmail
      - EMAIL_FROM=TaskManager <noreply@taskmanager.com>
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=samiulalimsaem@gmail.com
      - EMAIL_PASS=iulyukbuvpcdqjyw
      - FRONTEND_URL=http://localhost:3000
      - CLIENT_URL=http://localhost:3000
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - taskmanager-network
    depends_on:
      - backend
